name: Bump Version

on:
  push:
    branches:
      - main

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Get current tag
        id: get_tag
        run: echo "TAG=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV

      - name: Bump version
        id: bump_version
        run: echo "NEW_TAG=v$(echo $TAG | cut -c2- | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')" >> $GITHUB_ENV

      - name: Update tag
        run: git tag ${{ env.NEW_TAG }}

      - name: Push tag
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: ${{ env.NEW_TAG }}