name: Auto Increment Version Tag

on:
  push:
    branches:
      - main  # 或者你的默认分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16'

    - name: Bump version and push tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        CURRENT_VERSION=$(cat VERSION)
        MAJOR=$(echo $CURRENT_VERSION | cut -d . -f 1)
        MINOR=$(echo $CURRENT_VERSION | cut -d . -f 2)
        PATCH=$(echo $CURRENT_VERSION | cut -d . -f 3)
        NEW_VERSION="$MAJOR.$MINOR.$((PATCH + 1))"
        echo $NEW_VERSION > VERSION
        git add VERSION
        git commit -m "Bump version to $NEW_VERSION"
        git tag "v$NEW_VERSION"
        git push origin main --tags