name: Auto Increment Version Tag

on:
  push:
    branches:
      - main  # 或者你的默认分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16'

    - name: Install go-version
      run: go get github.com/hashicorp/go-version

    - name: Bump version and push tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        CURRENT_TAG=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo 'v0.1.8')
        CURRENT_VERSION=$(echo $CURRENT_TAG | cut -c 2-) 
        MAJOR=$(echo $CURRENT_VERSION | cut -d . -f 1)
        MINOR=$(echo $CURRENT_VERSION | cut -d . -f 2)
        PATCH=$(echo $CURRENT_VERSION | cut -d . -f 3)
        NEW_VERSION="v$MAJOR.$MINOR.$((PATCH + 1))"
        git tag $NEW_VERSION
        git push origin $NEW_VERSION